name: Build & Deploy to digitalocean
on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MindSpace app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir app
            cd app
            git clone git@github.com:kstch11/MindSpace.git
            echo 'cloned'
